### ISSUE TITLE
how to implement

### ISSUE THREAD

**Issue by Doc-ice** [MambaTheMaestro/BFACPv2_Fix#1]
Hi,
how would i implement this ?
just upload it to the domain ?

thanks

**Comment by MambaTheMaestro** [comment]
This is not a direct modification of the panel, instead it is a browser extension that injects javascript and css after the main page content is loaded. In this case, you would download either folder depending on your browser.

'BFACP Fix' is for Chromium based browsers (Edge and Google Chrome).
'FF BFACP Fix' is for Firefox.

Before installing, you would need to update the manifest.json. In the line that starts with "matches", you would replace the word 'hostname' with the public domain of your BFACP panel. Additionally, you can update the image included in the folder, if you rename it be sure to change the name of the file on the line starting with "default_icon" in the manifest.

As for installation, see below depending on your browser preference.

For Chromium based browsers, you would enable developer mode and load an unpacked extension then browse to the folder you downloaded.

For Firefox the process is a bit more involved, you can find more information about how to install it [here](https://extensionworkshop.com/documentation/develop/temporary-installation-in-firefox/), see the instructions listed below "To install an extension temporarily:".
